@echo off
set PATH=%~dp0bin;%~dp0python;%~dp0python\Scripts;%PATH%
echo [1/3] Testing psql.exe...
psql.exe --version
echo [2/3] Testing cloud-sql-proxy.exe...
cloud-sql-proxy.exe --version
echo [3/3] Testing python + psycopg2 + openpyxl...
python.exe -c "import psycopg2, openpyxl; print('psycopg2 version:', psycopg2.__version__); print('openpyxl version:', openpyxl.__version__); print('ALL BUNDLED TOOLS OPERATIONAL!')"
